# mengisi nilai dari variabel dari keboar menggunakan fungsi input()
var1 = input("masukkan angka 1= ")
var2 = input("masukkan angka 2= ")
print("Hasil inputan 1= ", var1 )
print("Hasil inputan 2= ", var2 )